// PRODUCTS ACTIONS
export const GET_HOME_PRODUCTS_SUCCESS = 'GET_HOME_PRODUCTS_SUCCESS';

// PRODUCT ACTIONS
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const GET_PRODUCT_DATA_SUCCESS = 'GET_PRODUCT_DATA_SUCCESS';

// CART ACTIONS
export const TOGGLE_PRODUCT_TO_CART_SUCCESS = 'TOGGLE_PRODUCT_TO_CART_SUCCESS';
export const GET_CART_PRODUCTS_SUCCESS = 'GET_CART_PRODUCTS_SUCCESS';
