//
//
// ADMIN ACTIONS
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS';
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS';
export const GET_ADMIN_ORDERS_SUCCESS = 'GET_ADMIN_ORDERS_SUCCESS';

// USER ACTIONS
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

// PRODUCTS ACTIONS
export const GET_HOME_PRODUCTS_SUCCESS = 'GET_HOME_PRODUCTS_SUCCESS';
export const GET_SEARCH_PRODUCTS_SUCCESS = 'GET_SEARCH_PRODUCTS_SUCCESS';
export const CREATE_FAKE_DATA_SUCCESS = 'CREATE_FAKE_DATA_SUCCESS';

// PRODUCT ACTIONS
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const GET_PRODUCT_DATA_SUCCESS = 'GET_PRODUCT_DATA_SUCCESS';

// CART ACTIONS
export const TOGGLE_PRODUCT_TO_CART_SUCCESS = 'TOGGLE_PRODUCT_TO_CART_SUCCESS';
export const GET_CART_PRODUCTS_SUCCESS = 'GET_CART_PRODUCTS_SUCCESS';
export const GET_CART_TOTALS_SUCCESS = 'GET_CART_TOTALS_SUCCESS';
export const GET_CART_PRODUCT_SUCCESS = 'GET_CART_PRODUCT_SUCCESS';
export const UPDATE_CART_PRODUCT_SUCCESS = 'UPDATE_CART_PRODUCT_SUCCESS';

// ORDERS ACTIONS
export const SET_NEW_ORDER_SUCCESS = 'SET_NEW_ORDER_SUCCESS';
export const GET_ORDERS_PRODUCTS_SUCCESS = 'GET_ORDERS_PRODUCTS_SUCCESS';
export const SET_ORDER_ITEM_SUCCESS = 'SET_ORDER_ITEM_SUCCESS';

// FAVORIT ACTIONS
export const TOGGLE_PRODUCT_TO_FAVORIT_SUCCESS =
  'TOGGLE_PRODUCT_TO_FAVORIT_SUCCESS';
export const GET_FAVORIT_PRODUCTS_SUCCESS = 'GET_FAVORIT_PRODUCTS_SUCCESS';
